module.exports = {
  rules: {
    'security-node/detect-absence-of-name-option-in-exrpress-session': 'warn',
    'security-node/detect-buffer-unsafe-allocation': 'warn',
    'security-node/detect-child-process': 'warn',
    'security-node/detect-crlf': 'warn',
    'security-node/detect-dangerous-redirects': 'warn',
    'security-node/detect-eval-with-expr': 'warn',
    'security-node/detect-html-injection': 'warn',
    'security-node/detect-improper-exception-handling': 'warn',
    'security-node/detect-insecure-randomness': 'warn',
    'security-node/detect-non-literal-require-calls': 'warn',
    'security-node/detect-nosql-injection': 'warn',
    'security-node/detect-option-multiplestatements-in-mysql': 'warn',
    'security-node/detect-option-rejectunauthorized-in-nodejs-httpsrequest': 'warn',
    'security-node/detect-option-unsafe-in-serialize-javascript-npm-package': 'warn',
    'security-node/detect-possible-timing-attacks': 'warn',
    'security-node/detect-runinthiscontext-method-in-nodes-vm': 'warn',
    'security-node/detect-security-missconfiguration-cookie': 'warn',
    'security-node/detect-sql-injection': 'warn',
    'security-node/detect-unhandled-async-errors': 'warn',
    'security-node/detect-unhandled-event-errors': 'warn',
    'security-node/disable-ssl-across-node-server': 'warn',
    'security-node/non-literal-reg-expr': 'warn',
  },
};
