name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
    - name: yarn install and test
      run: |
        yarn install
        yarn test
      env:
        CI: true
